[tool.poetry]
name = "dipdup tut"
version = "0.1.0"
description = ""
authors = ["karan"]

[tool.poetry.dependencies]
python = "^3.8"
dipdup = "^4.2.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
